### ISSUE TITLE
Pick up what's in the Writer's Guide and use?

### ISSUE THREAD

**Issue by thoni56** [alan-if/alan-docs#48]
There is a very preliminary [Author's Guide in the source](https://github.com/alan-if/alan/tree/master/doc/manual) (in Writing.odt) uploaded to website under [Development Snapshots](https://alanif.se/download-alan-v3/development-snapshots), perhaps somethings in it might be valuable. We should look through that and save what's valuable before removing it from the source tree and uploads.

**Comment by tajmone** [comment]
I actually had already converted all three documents to Asciidoc, and sent them to you in the past.

I can add them to the Manual folder in the Alan-Docs project, so we can easily copy and paste the required parts and edit them.

**Comment by thoni56** [comment]
Oh, sorry about that. As you can see, my alan work intensity is below the threshold of remembering things... But I'm trying to spend some more time on it for a while.

I didn't find the Author's Guide in the alan-docs project, so I thought they were not handled. Perhaps we should store them there, just to know where they are? And then it is easier to copy paste for anyone.

**Comment by tajmone** [comment]
I was mistaken, I've concerted only the ALAN design documents — which I've now added to the Beta7 work branch, in case we need to reuse some of their material.

But I can start working on the conversion of the Writing guide from ODT to AsciiDoc, and give it a rough polish. Then we can polish the parts that we decide to reuse, as we go along. 

Right now, having an AsciiDoc draft of the Writing guide in the repository (Beta7 branch) could help us discuss what to recycle.

**Comment by tajmone** [comment]
## Porting Work Started

I've began porting the _Alan Author's Guide_ to AsciiDoc, in a dedicated `writing-guide` branch:

https://github.com/alan-if/alan-docs/tree/writing-guide/writing

The document isn't huge, so it's worth porting it fully, and align it to the stylistic guides of the repository, so that it can then be further developed directly in the Alan Docs project.

Once it's nicely polished, we can merge it in `master` branch.

**Comment by tajmone** [comment]
## Porting Work Ready

@thoni56, I've completed porting the _Alan Author's Guide_ to AsciiDoc, and fixed all the styles according to the standards of this project.

I say that we should merge it into the `master` branch, if that's OK with you.

If you confirm, I'll do another quick check that everything is in place and then squash-merge it.

**Comment by thoni56** [comment]
Nice. Yes, please merge. There is nothing conflicting there and we should keep the number of branches low. Thanks.

**Comment by thoni56** [comment]
The preview links in the README for it seems to be wrong. (Didn't want to create an alan-docs issue for this ,-)

**Comment by tajmone** [comment]
Which is link is that? I can't find it. 

Maybe it was fixed with the merge into master now?

**Comment by tajmone** [comment]
Anyhow, I've squashed and deleted the `writing-guide` branch.

I couldn't find the broken link, they seem to work all fine now that it's merged. If you still find the link to be broken just drop some more info on which link is that, otherwise you can close the issue.

I have to run to a dinner with friends right now (  🍕 ), so I'll quit the PC....
